export function categoryEmoji(cat: string) {
  const c = cat.toLowerCase();
  if (c.includes("dairy") || c.includes("milk") || c.includes("yogurt") || c.includes("cheese") || c.includes("butter") || c.includes("egg")) return "🥛";
  if (c.includes("bakery") || c.includes("bread") || c.includes("baked") || c.includes("breakfast") || c.includes("dessert") || c.includes("scone")) return "🍞";
  if (c.includes("meat") || c.includes("poultry") || c.includes("butch") || c.includes("pork") || c.includes("beef") || c.includes("lamb") || c.includes("chicken") || c.includes("braai")) return "🥩";
  if (c.includes("fruit") || c.includes("vegetable") || c.includes("produce") || c.includes("veg")) return "🥬";
  if (c.includes("salad")) return "🥗";
  if (c.includes("fish") || c.includes("seafood") || c.includes("prawn")) return "🐟";
  if (c.includes("drink") || c.includes("beverage") || c.includes("coffee") || c.includes("juice") || c.includes("water") || c.includes("cordial") || c.includes("soft drink") || c.includes("hot drink")) return "🥤";
  if (c.includes("hand tool") || c.includes("tool") || c.includes("fixing") || c.includes("hardware") || c.includes("diy")) return "🔧";
  if (c.includes("paint") || c.includes("decorat")) return "🎨";
  if (c.includes("adhesive") || c.includes("sealant")) return "🧴";
  if (c.includes("security") || c.includes("lock")) return "🔒";
  if (c.includes("automotive") || c.includes("car ") || c.includes("fluid")) return "🚗";
  if (c.includes("electric")) return "⚡";
  if (c.includes("plumb") || c.includes("pipe")) return "🚿";
  if (c.includes("garden")) return "🌱";
  if (c.includes("hot food") || c.includes("hot meal") || c.includes("ready meal") || c.includes("quick meal") || c.includes("pizza") || c.includes("deli") || c.includes("platter")) return "🍲";
  if (c.includes("sandwich") || c.includes("wrap")) return "🥪";
  if (c.includes("snack") || c.includes("confection") || c.includes("chip") || c.includes("crisp") || c.includes("sweet") || c.includes("chocolate") || c.includes("nut")) return "🍪";
  if (c.includes("cleaning") || c.includes("laundry") || c.includes("household")) return "🧽";
  if (c.includes("beauty") || c.includes("personal") || c.includes("oral") || c.includes("feminine") || c.includes("shaving") || c.includes("cosmetic")) return "🧴";
  if (c.includes("frozen") || c.includes("ice cream")) return "🧊";
  if (c.includes("pantry") || c.includes("grocery") || c.includes("grain") || c.includes("oil") || c.includes("canned") || c.includes("pasta") || c.includes("cereal") || c.includes("sauce") || c.includes("cooking")) return "🥫";
  if (c.includes("fastener") || c.includes("building") || c.includes("cement") || c.includes("safety")) return "🧱";
  if (c.includes("baby")) return "🍼";
  if (c.includes("pharmacy") || c.includes("otc") || c.includes("vitamin") || c.includes("first aid")) return "💊";
  if (c.includes("paper") || c.includes("wrap") || c.includes("disposable")) return "🧻";
  if (c.includes("cookware") || c.includes("tableware") || c.includes("storage") || c.includes("kitchen") || c.includes("home essential")) return "🍳";
  if (c.includes("home") || c.includes("bedding") || c.includes("towel")) return "🏠";
  if (c.includes("pet") || c.includes("dog") || c.includes("cat")) return "🐶";
  if (c.includes("toy") || c.includes("game") || c.includes("puzzle")) return "🧸";
  if (c.includes("clothing") || c.includes("apparel") || c.includes("footwear") || c.includes("sock")) return "👕";
  if (c.includes("sport") || c.includes("fitness") || c.includes("exercise")) return "🏋️";
  if (c.includes("flower") || c.includes("bouquet")) return "💐";
  if (c.includes("stationery") || c.includes("writing") || c.includes("school")) return "📚";
  if (c.includes("party") || c.includes("seasonal") || c.includes("gift")) return "🎉";
  if (c.includes("specialty") || c.includes("international") || c.includes("organic") || c.includes("free from")) return "🌍";
  if (c.includes("appliance") || c.includes("electronic")) return "🔌";
  return "🛒";
}
