import { Store } from "./types";

export const STORES: Store[] = [
  {
    slug: "supermarket",
    name: "Aheers Supermarket",
    shortName: "Supermarket",
    tagline: "Fresh quality. Unbeatable prices.",
    description:
      "Your neighbourhood grocery store — household essentials, fresh produce, deli favourites, and Infinity Rewards member pricing.",
    address: "93 Voortrekker Street, Greytown, 3250",
    phone: "033 413 1156",
    accent: "aheers-green",
    accentBg: "bg-aheers-green",
    accentText: "text-aheers-green",
    icon: "🛒",
    type: "retail",
    delivery: true,
    pickup: true,
    status: "open",
    promotion: "Weekly specials — up to 30% off",
  },
  {
    slug: "powertrade",
    name: "Aheers PowerTrade",
    shortName: "PowerTrade",
    tagline: "Wholesale. Bulk. Delivered.",
    description:
      "Cash & carry wholesale for traders and businesses. Bulk orders, trade accounts, tele-orders, and delivery to outlining areas.",
    address: "93 Durban Street, Greytown, 3250",
    phone: "033 417 1049",
    accent: "powertrade-orange",
    accentBg: "bg-powertrade-orange",
    accentText: "text-powertrade-orange",
    icon: "📦",
    type: "wholesale",
    delivery: true,
    pickup: true,
    status: "open",
    promotion: "Trade bulk pricing — min qty discounts",
  },
  {
    slug: "buildsave",
    name: "Aheers Hardware",
    shortName: "Hardware",
    tagline: "Build it. Save on it.",
    description:
      "Hardware, building materials, paint, electrical, plumbing, garden and tools — contractor pricing and project quotes available.",
    address: "Greytown, KZN",
    phone: "033 413 1156",
    accent: "buildsave-slate",
    accentBg: "bg-buildsave-slate",
    accentText: "text-buildsave-slate",
    icon: "🔨",
    type: "hardware",
    delivery: true,
    pickup: true,
    status: "open",
    promotion: "Contractor bulk deals this month",
  },
  {
    slug: "foodworks",
    name: "Aheers Foodworks",
    shortName: "Foodworks",
    tagline: "Fresh food. Great value.",
    description:
      "Fresh food, deli, bakery and ready meals — quality ingredients and daily specials across the Aheers food format.",
    address: "93 Voortrekker Street, Greytown, 3250",
    phone: "033 413 1156",
    accent: "foodworks-red",
    accentBg: "bg-foodworks-red",
    accentText: "text-foodworks-red",
    icon: "🥩",
    type: "food",
    delivery: true,
    pickup: true,
    status: "open",
    promotion: "Fresh meat specials — weekends",
  },
  {
    slug: "grabngo",
    name: "Aheers Grab n Go",
    shortName: "Grab n Go",
    tagline: "Fresh. Fast. Ready in 10 min.",
    description:
      "Hot meals, baked goods, coffee and deli favourites — order ahead, express pickup, or quick delivery.",
    address: "93 Voortrekker Street, Greytown, 3250",
    phone: "066 529 0079",
    accent: "grabngo-teal",
    accentBg: "bg-grabngo-teal",
    accentText: "text-grabngo-teal",
    icon: "🥪",
    type: "takeaway",
    delivery: true,
    pickup: true,
    status: "open",
    promotion: "Coffee + scone combo R39.99",
  },
];

export function getStore(slug: string): Store | undefined {
  return STORES.find((s) => s.slug === slug);
}
